name: Build and Publish Docker
on:
  push:
    tags:
      - v*.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Docker Image from Repository
      uses: martyr30/actions/ssh-docker-run@master
      with:
        user: ${{ secrets.USER }}
        host: ${{ secrets.HOST }}
        dep_key: ${{ secrets.PRIVATE_KEY }}
        oauth: ${{ secrets.OAUTH }}
        registry: ${{ secrets.REGISTRY_ID }}
        service_name: traefik
